language: node_js

node_js:
    - "lts/*"

services:
    - "docker"


git:
    depth: false
      
addons:
    chrome: stable

env:
    - SITE_URL=http://0.0.0.0:4000/ JEKYLL_VERSION=3.8

before_install:
    - docker run -d  --rm -p "4000:4000" --volume="$PWD:/srv/jekyll" -it jekyll/jekyll:$JEKYLL_VERSION jekyll serve && sleep 10 && curl http://0.0.0.0:4000/ITStrategy/home.html | head -n4
    - sleep 20
    - docker container ls --all
    - curl http://0.0.0.0:4000/ITStrategy/home.html | head -n4

install:
    - "npm install axe-cli -g"
    - "npm install"
script:
    - git diff --name-only HEAD~15 | while read file; do node get-link-from-path.js $file; done | while read line; do axe $line --tags wcag2aa --exit; done